debug: False

frontends:
  test1:
    addr: 127.0.0.1:8080
    backend: test1
  test2:
    addr: 127.0.0.1:8081
    backend: test2

backends:
  test1:
    servers:
      - addr: 127.0.0.1:8090
      - addr: 127.0.0.1:8091
  test2:
    servers:
      - addr: 127.0.0.1:8091
